### ISSUE TITLE
More storyline

### ISSUE THREAD

**Issue by MikoWhy91** [RemoveIt/TibiaJS#12]
Please add more storyline because after 40 hours of gameplay it's hard to find something to do in this game.

**Comment by ralphcode** [comment]
@NikoWhy  How'd you get it running? Mine is always failing with;

> fs.js:646
>   return binding.open(pathModule._makeLong(path), stringToFlags(flags), mode);
> 
> Error: ENOENT: no such file or directory, open '..\tibiaJS\out\startMap.otbm'

**Comment by krtr** [comment]
@Ralpharoo hey, I have been busy for a last month, currently master is broken (i was trying to support otbm map format but without tibia dat file parsing it is out of question), I have created `old-map` branch which should work (if you use provided setup guide)

If it is still not working for you feel free to email me: krzszt@outlook.com
