### ISSUE TITLE
Amazing Project

### ISSUE THREAD

**Issue by ArunTeltia** [RemoveIt/TibiaJS#16]
Hello Sir,
I am Arun from India, I loved your project and want to congratulate you for making this great thing although I am late 

Sir Can you help me, I am watching on how to create map of the world did you type all the data ? can you help me how you get that data 
how you generated that data , I want to make this for bigger maps, can you guide me please, It will be great help 

Thank you

**Comment by krtr** [comment]
@ArunTeltia I used https://www.mapeditor.org/ to generate map
