### ISSUE TITLE
add nicks

### ISSUE THREAD

**Issue by krtr** [RemoveIt/TibiaJS#8]

**Comment by renatorib** [comment]
?

**Comment by krtr** [comment]
should be clear now :tomato:

**Comment by renatorib** [comment]
😂  now its clear

**Comment by geneotech** [comment]
idziemy łeb w łeb z gwiazdeczkami gościu. kto będzie miał więcej kto będzie miał więcej!!!!!!!!!!!!!!!!!!!!!

**Comment by krtr** [comment]
propably needs some account infrastructure closing for now
